server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydemo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    #    url: jdbc:mysql://127.0.0.1:3306/pointquery?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    #    username: root
    #    password: 123456
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

dubbo:
  application:
    name: dubbo-service
    metadata-type: local
  scan:
    base-packages: com.mydubbo.service.impl   # Base packages to scan Dubbo Component: @com.alibaba.dubbo.config.annotation.Service
  protocol: # Dubbo Protocol
    name: dubbo
    port: 29081
  registry: # 注册中心
    address: 127.0.0.1:8848?namespace=my001
#    address: 172.16.21.74:8848?namespace=89c61f85-6223-48a3-9ff5-322e62a5e4cd
    protocol: nacos
#    simplified: true
  provider:
    delay: -1
    filter: -exception
  consumer:
    retries: 0
#  config-center:
#    highest-priority: false
#    address: nacos://127.0.0.1:8848?namespace=my002
#  metadata-report: # 元数据中心
#    address: redis://127.0.0.1:6379

nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: my002
