server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydemo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    #    url: jdbc:mysql://127.0.0.1:3306/pointquery?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    #    username: root
    #    password: 123456
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

dubbo:
  application:
    name: dubbo-service
  scan:
    base-packages: com.mydubbo.service.impl   # Base packages to scan Dubbo Component: @com.alibaba.dubbo.config.annotation.Service
  protocol: # Dubbo Protocol
    name: dubbo
    port: 29081
  registry: # Dubbo Registry
    address: 172.16.21.74:8848?namespace=89c61f85-6223-48a3-9ff5-322e62a5e4cd
    protocol: nacos
  provider:
    delay: -1
  consumer:
    retries: 0